services:
  nuedgewise:
    image: nuedgewise:v1
    command: bash
    stdin_open: true  # `-i`
    tty: true         # `-t`
    restart: no       # `--rm`
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ../ML_KWS:/ML_KWS
      - ../ML_Image_Classification:/ML_Image_Classification
    ports:
      - '8888:8888'  
    privileged: true
    #use the host's network interfaces directly
    network_mode: host  
